name: Node App Git Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Action1
        run: echo "Hello World from GitHub Actions! develop "
name: Node App Git Actions 2
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Action1
        run: echo "Hello World from GitHub Actions! develop "